{% set name = "branca" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/branca-{{ version }}.tar.gz
  sha256: 55949855214504c7583b71b9a03a84dce2e96a84027613bb53b42d04844ce24e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - setuptools
    - jinja2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - branca

about:
  home: https://github.com/python-visualization/branca
  license: MIT
  license_file: LICENSE.txt
  summary: This library is a spinoff from folium with the non-map-specific features

extra:
  recipe-maintainers:
    - BibMartin
    - ocefpaf
